title: PeproDev Ultimate Invoice
description: The most complete invoice plugin you will ever need. Easily create HTML/PDF invoices for your WC orders, in a beautiful style and e-mail it to your customers. 
theme: modernist
show_downloads: true

# Include the README.md file as the homepage
defaults:
  - scope:
      path: "" # all files in the root
      type: "pages"
    values:
      permalink: /:basename/

# Exclude index.html so README.md takes priority
exclude:
  - index.html

# Build settings
plugins:
  - jekyll-redirect-from

# Redirect index.html to README.md if someone directly accesses it
redirect_from:
  - /index.html
